[package]
name = "mod-filesystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filenamegen = "0.2"
anyhow = "1.0"
config = { path = "../config" }
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
tokio = {workspace=true}
lruttl = {path="../lruttl"}
once_cell = "1.17"
