[package]
name = "mod-smtp-response-normalize"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
config = {path="../config"}
memchr.workspace = true
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
phf = "0.13"
regex.workspace = true
uuid.workspace = true

[dev-dependencies]
criterion = {workspace=true}
k9.workspace = true

[[bench]]
name = "normalizer"
harness = false
