services:
  sink:
    container_name: kumo-sink
    hostname: sinkinator
    # use the latest build from `main`
    image: ghcr.io/kumocorp/kumomta-dev:latest
    # alternatively, use the latest stable release
    #image: ghcr.io/kumocorp/kumomta:latest
    volumes:
      - ./policy:/opt/kumomta/etc/policy
    restart: unless-stopped
    ports:
      - 2525:25
