[package]
name = "mod-digest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = {workspace=true}
aws-lc-rs.workspace = true
config = {path="../config"}
crc32fast = {workspace=true}
data-encoding = {workspace=true}
data-loader = {path="../data-loader"}
mlua = {workspace=true, features=["serialize"]}
serde_json = {workspace=true}
