[package]
name = "integration-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
axum = {workspace=true}
axum-server = {workspace=true}
k9 = "0.12"
kumo-api-types = {path="../kumo-api-types"}
kumo-log-types = {path="../kumo-log-types"}
lipsum = "0.9"
maildir = {path="../maildir"}
mailparsing = {path="../mailparsing"}
nix = {version="0.29", features=["signal", "user"]}
rfc5321 = {path="../rfc5321"}
serde = "1.0"
serde_json = "1.0"
sqlite = {workspace=true}
tempfile = {workspace=true}
textwrap = "0.16"
tokio = {workspace=true, features=["full"]}
zstd = "0.13"
