[package]
name = "mod-redis"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
duration-serde = {path="../duration-serde"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
once_cell = "1.17"
mobc = "0.8"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
redis = {version="0.26", features=["cluster", "cluster-async", "connection-manager", "tokio-comp"]}
tokio = {workspace=true, features=["rt", "tracing", "process", "io-util", "io-std", "macros", "time"]}
tempfile = {workspace=true}

[dev-dependencies]
which = "4.4"
