[package]
name = "rfc5321"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["client"]
client = ["dep:openssl", "dep:tokio-rustls", "dep:tokio-openssl", "dep:tracing", "dep:tokio", "dep:hickory-proto", "dep:webpki-roots"]

[dependencies]
data-encoding = {workspace=true}
duration-serde = {path="../duration-serde"}
libc = "0.2"
memchr = "2.5"
once_cell = "1.17"
openssl = {workspace=true, optional=true}
pest = "2.7"
pest_derive = "2.7"
serde = {version="1.0", features=["derive"]}
thiserror = "1.0"
tokio = {workspace=true, features=["full"], optional=true}
tokio-rustls = {workspace=true, features=["dangerous_configuration"], optional=true}
tokio-openssl = {version="0.6.4", optional=true}
tracing = {version="0.1", optional=true}
hickory-proto = {workspace=true, optional=true}
webpki-roots = {workspace=true, optional=true}
