[package]
name = "mod-time"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
config = {path="../config"}
humantime.workspace = true
linkme.workspace = true
kumo-prometheus = { path = "../kumo-prometheus" }
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
tokio.workspace = true
