[package]
name = "mod-nats"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
async-nats = { workspace = true, features = [
    "server_2_10",
    "server_2_11",
    "server_2_12",
    "ring",
] }
config = { path = "../config" }
data-loader = { path = "../data-loader", default-features = false }
duration-serde = { path = "../duration-serde" }
mlua = { workspace = true, features = [
    "vendored",
    "lua54",
    "async",
    "send",
    "serialize",
] }
serde.workspace = true
serde_bytes.workspace = true
