[package]
name = "mailparsing"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = {workspace=true}
charset-normalizer-rs.workspace = true
chrono = {workspace=true, default-features=false, features=["std", "clock"]}
data-encoding = {workspace=true}
data-encoding-macro = {workspace=true}
kumo-wrap = {path="../kumo-wrap"}
memchr = {workspace=true}
nom = {workspace=true}
nom_locate = {workspace=true}
pastey = {workspace=true}
quoted_printable = {workspace=true}
serde = {workspace=true}
thiserror = {workspace=true}
uuid = {workspace=true, features=["v4", "fast-rng"]}

[dev-dependencies]
k9 = {workspace=true}
