[package]
name = "regex-set-map"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
config = {path="../config"}
mod-memoize = {path="../mod-memoize"}
mlua = {workspace=true, features=["vendored", "lua54", "async", "send", "serialize"]}
regex = "1.7"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
