[package]
name = "kumo-api-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime-serde = "1.1"
serde = {version="1.0", features=["derive"]}
serde_json = "1.0"
spool = {path="../spool"}
uuid = {version="1.3", features=["serde"]}
url = "2.4"
